-- 무서운이야기 테이블
create table HORROR_STORY
(
    --HORR_ST_NO bigint generated by default as identity NOT NULL, --H2 version
    HORR_ST_NO bigint NOT NULL auto_increment,
    VIEW_COUNT int default 0,
    TITLE varchar(255),
    CONTENT varchar(4000),
    IS_DELETE char(1) default 'N',
    ENTER_BY varchar(40),
    ENTER_DATE datetime,
    UPDATE_BY varchar(40),
    UPDATE_DATE datetime,
    PRIMARY KEY (HORR_ST_NO)
)


-- 첨부파일 테이블
create table FILE
(
    FILE_NO bigint NOT NULL auto_increment,
    FILE_NAME varchar(4000),
    FILE_PATH varchar(4000),
    ATTACH_TYPE varchar(100),
    ATTACH_NO bigint,
    CONTENT_TYPE varchar(100),
    ENTER_BY varchar(40),
    ENTER_DATE datetime,
    UPDATE_BY varchar(40),
    UPDATE_DATE datetime,
    PRIMARY KEY (FILE_NO)
)

-- 회원
create table MEMBER
(
    MEMBER_NO bigint NOT NULL auto_increment,
    LOGIN_ID varchar(100),
    PASSWORD varchar(2000),
    NAME varchar(100),
    PHONE varchar(100),
    EMAIL varchar(100),
    ADDRESS varchar(2000),
    HOBBY varchar(2000),
    ENTER_BY varchar(40),
    ENTER_DATE datetime,
    UPDATE_BY varchar(40),
    UPDATE_DATE datetime,
    PRIMARY KEY (MEMBER_NO)
)