-- 무서운이야기 테이블
create table HORROR_STORY
(
    --HORR_ST_NO bigint generated by default as identity NOT NULL, --H2 version
    HORR_ST_NO bigint NOT NULL auto_increment,
    VIEW_COUNT int default 0,
    TITLE varchar(255),
    CONTENT varchar(4000),
    ENTER_BY varchar(40),
    ENTER_DATE datetime,
    UPDATE_BY varchar(40),
    UPDATE_DATE datetime,
    PRIMARY KEY (HORR_ST_NO)
)