-- 무서운이야기 테이블
create table HORROR_STORY
(
    horrStNo bigint generated by default as identity NOT NULL,
    viewCount int,
    title varchar(255),
    content varchar(4000),
    enterBy varchar(40),
    enterDate date,
    updateBy varchar(40),
    updateDate date,
    primary key (horrStNo)
)